### ISSUE TITLE
instance not registering at the WMSPanel

### ISSUE THREAD

**Issue by aharonamir** [rjrivero/docker-nimble#3]
Hello,
I have run the docker:
docker run --rm -p 8081:8081 -p 1935:1935 \
    -e WMSPANEL_USER=[myemail] \
    -e WMSPANEL_PASS=[mypass]  \
    --name nimble rjrivero/nimble
I get:

> *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
> *** Running /etc/my_init.d/10_syslog-ng.init...
> May 15 10:20:18 amir244 syslog-ng[10]: syslog-ng starting up; version='3.5.6'
> May 15 10:20:19 amir244 syslog-ng[10]: EOF on control channel, closing connection;
> *** Running /etc/my_init.d/nimble_reg...
> Welcome to WMSPanel Nimble Streamer registration utility.
> Welcome to WMSPanel Nimble Streamer registration utility.
> *** Running /etc/rc.local...
> *** Booting runit daemon...
> *** Runit started as PID 24
> May 15 10:20:19 amir244 cron[28]: (CRON) INFO (pidfile fd = 3)
> May 15 10:20:19 amir244 cron[28]: (CRON) INFO (Running @reboot jobs)
> 

But I don't see the server in the server's lst in the WMSPanel.
When i've installed the server on my machine (ubuntu) using this link:
https://wmspanel.com/nimble/install#os_ubuntu
It was ok and the server on my machine registered successfully.
What cab be the problem?

**Comment by rjrivero** [comment]
Hi, sorry but it's been so long since I last used this software... I'm not supporting it anymore. Maybe it's just that the WMS version in the container is so old that it doesn't work with their current portal. You might want to try to clone the repo and build the container with the latest version. If you manage to make it work and want to make a pull request, I'll gladly accept it.
